# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_itembrowser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_itembrowser(object):
    def setupUi(self, itembrowser):
        itembrowser.setObjectName("itembrowser")
        itembrowser.resize(270, 150)
        itembrowser.setWindowTitle("Item Browser")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browseFrame = QtWidgets.QFrame(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseFrame.sizePolicy().hasHeightForWidth())
        self.browseFrame.setSizePolicy(sizePolicy)
        self.browseFrame.setAutoFillBackground(False)
        self.browseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.browseFrame.setObjectName("browseFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.browseFrame)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentPosLabel = QtWidgets.QLabel(self.browseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentPosLabel.sizePolicy().hasHeightForWidth())
        self.currentPosLabel.setSizePolicy(sizePolicy)
        self.currentPosLabel.setToolTip("")
        self.currentPosLabel.setAccessibleName("")
        self.currentPosLabel.setAccessibleDescription("")
        self.currentPosLabel.setText("0/0")
        self.currentPosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPosLabel.setObjectName("currentPosLabel")
        self.horizontalLayout.addWidget(self.currentPosLabel)
        self.previousButton = QtWidgets.QToolButton(self.browseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.previousButton.setToolTip("")
        self.previousButton.setAccessibleName("")
        self.previousButton.setAccessibleDescription("")
        self.previousButton.setText("<")
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.listCombo = QtWidgets.QComboBox(self.browseFrame)
        self.listCombo.setToolTip("")
        self.listCombo.setAccessibleName("")
        self.listCombo.setAccessibleDescription("")
        self.listCombo.setEditable(False)
        self.listCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.listCombo.setObjectName("listCombo")
        self.horizontalLayout.addWidget(self.listCombo)
        self.nextButton = QtWidgets.QToolButton(self.browseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.nextButton.setToolTip("")
        self.nextButton.setAccessibleName("")
        self.nextButton.setAccessibleDescription("")
        self.nextButton.setText(">")
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.panCheck = QtWidgets.QCheckBox(self.browseFrame)
        self.panCheck.setChecked(True)
        self.panCheck.setObjectName("panCheck")
        self.horizontalLayout_2.addWidget(self.panCheck)
        self.scaleCheck = QtWidgets.QCheckBox(self.browseFrame)
        self.scaleCheck.setObjectName("scaleCheck")
        self.horizontalLayout_2.addWidget(self.scaleCheck)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.actionButton = QtWidgets.QToolButton(self.browseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionButton.sizePolicy().hasHeightForWidth())
        self.actionButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/action.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionButton.setIcon(icon)
        self.actionButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.actionButton.setObjectName("actionButton")
        self.horizontalLayout_2.addWidget(self.actionButton)
        self.editFormButton = QtWidgets.QToolButton(self.browseFrame)
        self.editFormButton.setToolTip("")
        self.editFormButton.setAccessibleDescription("")
        self.editFormButton.setText("...")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/openform.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editFormButton.setIcon(icon1)
        self.editFormButton.setObjectName("editFormButton")
        self.horizontalLayout_2.addWidget(self.editFormButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.browseFrame, 0, 1, 1, 1)
        itembrowser.setWidget(self.dockWidgetContents)

        self.retranslateUi(itembrowser)
        QtCore.QMetaObject.connectSlotsByName(itembrowser)

    def retranslateUi(self, itembrowser):
        _translate = QtCore.QCoreApplication.translate
        self.panCheck.setText(_translate("itembrowser", "pan"))
        self.scaleCheck.setText(_translate("itembrowser", "scale"))
        self.actionButton.setText(_translate("itembrowser", "..."))

